# -*- coding: utf-8 -*-
"""pipeline_agentes_iris.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pwsl8dMrMf10z3C_-Fda8iI6okowSjRG

### **Librerias**
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, f1_score

"""### **Dataset CSV**"""

from google.colab import files
subido = files.upload()          # abre un botón para elegir tu archivo

nombre = list(subido.keys())[0]
df = pd.read_csv(nombre)

# Columnas del dataset Iris
caracteristicas = ["sepal_length", "sepal_width", "petal_length", "petal_width"]
TARGET = "species"

X = df[caracteristicas]
y = df[TARGET]

print("Archivo cargado:", nombre)
print("Columnas:", list(df.columns))
print(df.head())
print("\nFaltantes:\n", df.isnull().sum())
print("\nEspecies a predecir:", y.unique())

"""### **Normalizar Dataset**"""

def agente_normalizador(X):
    num = X.select_dtypes(include=np.number).columns.tolist()
    cat = X.select_dtypes(exclude=np.number).columns.tolist()

    pipe_num = Pipeline([
        ("imputar", SimpleImputer(strategy="median")),
        ("escalar", StandardScaler())
    ])
    pipe_cat = Pipeline([
        ("imputar", SimpleImputer(strategy="most_frequent")),
        ("codificar", OneHotEncoder(handle_unknown="ignore"))
    ])
    pre = ColumnTransformer([
        ("num", pipe_num, num),
        ("cat", pipe_cat, cat)
    ])
    return pre, num, cat

preprocesador, num, cat = agente_normalizador(X)
print("Dataset limpio listo.")
print("Numéricas:", num)
print("Categóricas:", cat)

"""### **Entrenador**"""

def agente_entrenador(preprocesador, X, y):
    X_tr, X_te, y_tr, y_te = train_test_split(
        X, y, test_size=0.2, random_state=42, stratify=y)

    candidatos = {
        "RandomForest": RandomForestClassifier(random_state=42),
        "LogisticRegression": LogisticRegression(max_iter=1000)
    }

    resultados = {}
    for nombre, modelo in candidatos.items():
        pipe = Pipeline([("pre", preprocesador), ("modelo", modelo)])
        score_cv = cross_val_score(pipe, X_tr, y_tr, cv=5, scoring="f1_weighted").mean()
        resultados[nombre] = (pipe, score_cv)
        print(f"{nombre}: F1 validación cruzada = {score_cv:.3f}")

    mejor = max(resultados, key=lambda k: resultados[k][1])
    pipe_mejor = resultados[mejor][0].fit(X_tr, y_tr)

    pred = pipe_mejor.predict(X_te)
    metricas = {
        "modelo": mejor,
        "f1_cv": round(resultados[mejor][1], 3),
        "accuracy_test": round(accuracy_score(y_te, pred), 3),
        "f1_test": round(f1_score(y_te, pred, average="weighted"), 3)
    }
    return pipe_mejor, metricas

modelo_final, metricas = agente_entrenador(preprocesador, X, y)
print("\n Métricas + modelo:", metricas)

"""### **Comunicador**"""

def agente_comunicador(metricas):
    desempeno = "sólido" if metricas["f1_test"] > 0.8 else "aceptable"
    reporte = (
        f"REPORTE FINAL\n"
        f"-------------\n"
        f"Se evaluaron varios modelos usando validación cruzada de 5 particiones.\n"
        f"El mejor modelo fue {metricas['modelo']}, con un F1 en validación de "
        f"{metricas['f1_cv']}.\n"
        f"En el conjunto de prueba alcanzó una exactitud de {metricas['accuracy_test']} "
        f"y un F1 de {metricas['f1_test']}.\n"
        f"Esto indica un desempeño {desempeno} para predecir la especie de la flor (Iris)."
    )
    return reporte

print(agente_comunicador(metricas))